import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'it' | 'fr' | 'pt';
export type Theme = 'light' | 'dark';

interface SettingsContextType {
  language: Language;
  theme: Theme;
  setLanguage: (lang: Language) => void;
  setTheme: (theme: Theme) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    loans: 'Loans',
    budget: 'Budget',
    goals: 'Goals',
    assets: 'Assets',
    settings: 'Settings',
    export: 'Export Data',
    import: 'Import Data',
    summary: 'General Summary',
    monthlyBalance: 'Monthly Balance',
    netWorth: 'Net Worth',
    goalProgress: 'Goal Progress',
    incomeVsExpenses: 'Income vs Expenses',
    debtDistribution: 'Debt Distribution',
    newLoan: 'New Loan',
    newGoal: 'New Goal',
    newAsset: 'New Asset',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    description: 'Description',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    income: 'Income',
    expense: 'Expense',
    add: 'Add',
    total: 'Total',
    balance: 'Balance',
    premiumPlan: 'Premium Plan',
    mortgage: 'Mortgage',
    auto: 'Auto',
    loanName: 'Loan Name',
    annualRate: 'Annual Rate',
    years: 'Years',
    insurance: 'Insurance',
    vat: 'VAT',
    startDate: 'Start Date',
    extraPayment: 'Extra Payment',
    recurringExtraPayment: 'Recurring Extra Payment',
    remainingMonths: 'Remaining Months',
    interest: 'Interest',
    principal: 'Principal',
    remainingBalance: 'Remaining Balance',
    month: 'Month',
    months: 'Months',
    apply: 'Apply',
    schedule: 'Schedule',
    activeSchedules: 'Active Schedules',
    realizedPayments: 'Realized Payments',
    targetAmount: 'Target Amount',
    currentAmount: 'Current Amount',
    deadline: 'Deadline',
    savings: 'Savings',
    investment: 'Investment',
    assetName: 'Asset Name',
    estimatedValue: 'Estimated Value',
    passiveIncome: 'Passive Income',
    property: 'Property',
    other: 'Other',
    assetsSummary: 'Assets Summary',
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    updateProgress: 'Update Progress',
    addAmount: 'Add Amount',
    goalName: 'Goal Name',
    help: 'Help',
    helpDescription: 'Learn how to use the application features.',
    loansHelp: 'Manage your loans and see their amortization schedule.',
    budgetHelp: 'Track your daily income and expenses.',
    goalsHelp: 'Set savings and investment targets and track progress.',
    assetsHelp: 'Monitor your properties and net worth.',
    settingsHelp: 'Customize your experience and manage data.',
    financialTips: 'Financial Tips',
    getSmartAdvice: 'Get Smart Advice',
    analyzingFinances: 'Analyzing your finances...',
    tipsDescription: 'Personalized recommendations to improve your financial health.',
    noTipsYet: 'Click the button to get personalized financial advice based on your data.',
    aiAdvice: 'AI Financial Advice',
    totalInterestPaid: 'Total Interest Paid',
    totalInterestPending: 'Total Interest Pending',
    finalPayoffDate: 'Final Payoff Date',
    projectionYears: 'Projection (Years)',
    advisorFocus: 'Financial Advisor Focus',
    priorities: 'Priorities',
    alternatives: 'Alternatives',
    budgetAnalysis: 'Budget Analysis',
    loanStrategies: 'Loan Strategies',
    generalStrategy: 'General Strategy',
    analysisType: 'Analysis Type',
    potentialSavings: 'Potential Savings',
    qualityOfLife: 'Quality of Life',
    interestSavings: 'Interest Savings',
    coveredByOthers: 'Covered by Others',
    family: 'Family',
    shared: 'Shared',
    externalExpense: 'External Expense (Not from personal income)',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    totalCoveredByOthers: 'Total Covered by Others',
    debtTimeline: 'Debt Timeline',
    debtAnalyzer: 'Debt Health Analyzer',
    overIndebtedness: 'Over-indebtedness Risk',
    financialFreedom: 'Path to Financial Freedom',
    efficiencyScore: 'Financial Efficiency Score',
    optimizationFocus: 'Strict Optimization Focus',
    globalVision: 'Global Interest Vision',
    viableAlternatives: 'Viable Alternatives',
    debtFreeDate: 'Estimated Debt-Free Date',
    interestAvoided: 'Potential Interest Avoided',
    totalDebtPending: 'Total Outstanding Debt',
    totalSavings: 'Total Savings (Avoided)',
    timeSaved: 'Time Saved',
    moneySaved: 'Money Saved',
    totalAvoided: 'Total Avoided (Interest, VAT, Insurance)'
  },
  es: {
    dashboard: 'Dashboard',
    loans: 'Préstamos',
    budget: 'Presupuesto',
    goals: 'Metas',
    assets: 'Patrimonio',
    settings: 'Configuración',
    export: 'Exportar Datos',
    import: 'Importar Datos',
    summary: 'Resumen General',
    monthlyBalance: 'Balance Mensual',
    netWorth: 'Patrimonio Neto',
    goalProgress: 'Progreso de Metas',
    incomeVsExpenses: 'Ingresos vs Gastos',
    debtDistribution: 'Distribución de Deuda',
    newLoan: 'Nuevo Préstamo',
    newGoal: 'Nueva Meta',
    newAsset: 'Nuevo Activo',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    description: 'Descripción',
    amount: 'Monto',
    category: 'Categoría',
    date: 'Fecha',
    income: 'Ingreso',
    expense: 'Gasto',
    add: 'Agregar',
    total: 'Total',
    balance: 'Balance',
    premiumPlan: 'Plan Premium',
    mortgage: 'Hipotecario',
    auto: 'Automotriz',
    loanName: 'Nombre del Préstamo',
    annualRate: 'Tasa Anual',
    years: 'Años',
    insurance: 'Seguro',
    vat: 'IVA',
    startDate: 'Fecha de Inicio',
    extraPayment: 'Pago Extra',
    recurringExtraPayment: 'Pago Extra Recurrente',
    remainingMonths: 'Meses Restantes',
    interest: 'Interés',
    principal: 'Capital',
    remainingBalance: 'Saldo',
    month: 'Mes',
    months: 'Meses',
    apply: 'Aplicar',
    schedule: 'Programar',
    activeSchedules: 'Programaciones Activas',
    realizedPayments: 'Abonos Realizados',
    targetAmount: 'Monto Objetivo',
    currentAmount: 'Monto Actual',
    deadline: 'Fecha Límite',
    savings: 'Ahorro',
    investment: 'Inversión',
    assetName: 'Nombre del Activo',
    estimatedValue: 'Valor Estimado',
    passiveIncome: 'Ingreso Pasivo',
    property: 'Propiedad',
    other: 'Otro',
    assetsSummary: 'Resumen de Patrimonio',
    totalAssets: 'Total Activos',
    totalLiabilities: 'Total Pasivos',
    updateProgress: 'Actualizar Avance',
    addAmount: 'Agregar Monto',
    goalName: 'Nombre de la Meta',
    help: 'Ayuda',
    helpDescription: 'Aprende a usar las funcionalidades de la aplicación.',
    loansHelp: 'Gestiona tus préstamos y consulta su tabla de amortización.',
    budgetHelp: 'Registra tus ingresos y gastos diarios.',
    goalsHelp: 'Establece objetivos de ahorro e inversión y sigue tu progreso.',
    assetsHelp: 'Monitorea tus propiedades y patrimonio neto.',
    settingsHelp: 'Personaliza tu experiencia y gestiona tus datos.',
    financialTips: 'Consejos Financieros',
    getSmartAdvice: 'Obtener Consejos Inteligentes',
    analyzingFinances: 'Analizando tus finanzas...',
    tipsDescription: 'Recomendaciones personalizadas para mejorar tu salud financiera.',
    noTipsYet: 'Haz clic en el botón para obtener consejos financieros personalizados basados en tus datos.',
    aiAdvice: 'Consejos de IA',
    totalInterestPaid: 'Interés Total Pagado',
    totalInterestPending: 'Interés Total Pendiente',
    finalPayoffDate: 'Fecha Final de Cancelación',
    projectionYears: 'Proyección (Años)',
    advisorFocus: 'Enfoque de Asesor Financiero',
    priorities: 'Prioridades',
    alternatives: 'Alternativas',
    budgetAnalysis: 'Análisis de Presupuesto',
    loanStrategies: 'Estrategias de Préstamos',
    generalStrategy: 'Estrategia General',
    analysisType: 'Tipo de Análisis',
    potentialSavings: 'Ahorro Potencial',
    qualityOfLife: 'Calidad de Vida',
    interestSavings: 'Ahorro de Intereses',
    coveredByOthers: 'Cubierto por Otros',
    family: 'Familia',
    shared: 'Compartido',
    externalExpense: 'Gasto Externo (No afecta ingreso personal)',
    totalIncome: 'Total de Ingresos',
    totalExpenses: 'Total de Gastos',
    totalCoveredByOthers: 'Total Cubierto por Otros',
    debtTimeline: 'Línea de Tiempo de Deuda',
    debtAnalyzer: 'Analizador de Salud de Deuda',
    overIndebtedness: 'Riesgo de Sobreendeudamiento',
    financialFreedom: 'Camino a la Libertad Financiera',
    efficiencyScore: 'Puntaje de Eficiencia Financiera',
    optimizationFocus: 'Enfoque Estricto de Optimización',
    globalVision: 'Visión Global de Intereses',
    viableAlternatives: 'Alternativas Viables',
    debtFreeDate: 'Fecha Estimada de Libertad de Deuda',
    interestAvoided: 'Interés Potencial Evitado',
    totalDebtPending: 'Total Deuda Pendiente',
    totalSavings: 'Ahorro Total (Evitado)',
    timeSaved: 'Tiempo Ahorrado',
    moneySaved: 'Dinero Ahorrado',
    totalAvoided: 'Total Evitado (Intereses, IVA, Seguros)'
  },
  it: {
    dashboard: 'Dashboard',
    loans: 'Prestiti',
    budget: 'Bilancio',
    goals: 'Obiettivi',
    assets: 'Patrimonio',
    settings: 'Impostazioni',
    export: 'Esporta Dati',
    import: 'Importa Dati',
    summary: 'Riepilogo Generale',
    monthlyBalance: 'Bilancio Mensile',
    netWorth: 'Patrimonio Netto',
    goalProgress: 'Progresso Obiettivi',
    incomeVsExpenses: 'Entrate vs Uscite',
    debtDistribution: 'Distribuzione Debito',
    newLoan: 'Nuovo Prestito',
    newGoal: 'Nuovo Obiettivo',
    newAsset: 'Nuovo Asset',
    language: 'Lingua',
    theme: 'Tema',
    darkMode: 'Modalità Scura',
    lightMode: 'Modalità Chiara',
    save: 'Salva',
    cancel: 'Annulla',
    edit: 'Modifica',
    delete: 'Elimina',
    description: 'Descrizione',
    amount: 'Importo',
    category: 'Categoria',
    date: 'Data',
    income: 'Entrata',
    expense: 'Uscita',
    add: 'Aggiungi',
    total: 'Totale',
    balance: 'Bilancio',
    premiumPlan: 'Piano Premium',
    mortgage: 'Mutuo',
    auto: 'Auto',
    loanName: 'Nome Prestito',
    annualRate: 'Tasso Annuo',
    years: 'Anni',
    insurance: 'Assicurazione',
    vat: 'IVA',
    startDate: 'Data Inizio',
    extraPayment: 'Pagamento Extra',
    recurringExtraPayment: 'Pagamento Extra Ricorrente',
    remainingMonths: 'Mesi Rimanenti',
    interest: 'Interessi',
    principal: 'Capitale',
    remainingBalance: 'Saldo Residuo',
    month: 'Mese',
    months: 'Mesi',
    apply: 'Applica',
    schedule: 'Pianifica',
    activeSchedules: 'Pianificazioni Attive',
    realizedPayments: 'Pagamenti Effettuati',
    targetAmount: 'Importo Obiettivo',
    currentAmount: 'Importo Attuale',
    deadline: 'Scadenza',
    savings: 'Risparmi',
    investment: 'Investimento',
    assetName: 'Nome Asset',
    estimatedValue: 'Valore Stimato',
    passiveIncome: 'Rendita Passiva',
    property: 'Proprietà',
    other: 'Altro',
    assetsSummary: 'Riepilogo Patrimonio',
    totalAssets: 'Totale Attività',
    totalLiabilities: 'Totale Passività',
    updateProgress: 'Aggiorna Progresso',
    addAmount: 'Aggiungi Importo',
    goalName: 'Nome Obiettivo',
    help: 'Aiuto',
    helpDescription: 'Scopri come utilizzare le funzionalità dell\'applicazione.',
    loansHelp: 'Gestisci i tuoi prestiti e visualizza il piano di ammortamento.',
    budgetHelp: 'Tieni traccia delle tue entrate e uscite quotidiane.',
    goalsHelp: 'Imposta obiettivi di risparmio e investimento e segui i progressi.',
    assetsHelp: 'Monitora le tue proprietà e il patrimonio netto.',
    settingsHelp: 'Personalizza la tua esperienza e gestisci i dati.',
    financialTips: 'Consigli Finanziari',
    getSmartAdvice: 'Ottieni Consigli Intelligenti',
    analyzingFinances: 'Analisi delle tue finanze...',
    tipsDescription: 'Raccomandazioni personalizzate per migliorare la tua salute finanziaria.',
    noTipsYet: 'Clicca sul pulsante per ottenere consigli finanziari personalizzati basati sui tuoi dati.',
    aiAdvice: 'Consigli IA',
    totalInterestPaid: 'Interesse Totale Pagato',
    totalInterestPending: 'Interesse Totale Pendente',
    finalPayoffDate: 'Data Finale di Estinzione',
    projectionYears: 'Proiezione (Anni)',
    advisorFocus: 'Focus Consulente Finanziario',
    priorities: 'Priorità',
    alternatives: 'Alternative',
    budgetAnalysis: 'Analisi del Budget',
    loanStrategies: 'Strategie di Prestito',
    generalStrategy: 'Strategia Generale',
    analysisType: 'Tipo di Analisi',
    potentialSavings: 'Risparmio Potenziale',
    qualityOfLife: 'Qualità della Vita',
    interestSavings: 'Risparmio sugli Interessi',
    coveredByOthers: 'Coperto da Altri',
    family: 'Famiglia',
    shared: 'Condiviso',
    externalExpense: 'Spesa Esterna (Non influisce sul reddito personale)',
    totalIncome: 'Entrate Totali',
    totalExpenses: 'Uscite Totali',
    totalCoveredByOthers: 'Totale Coperto da Altri',
    debtTimeline: 'Cronologia del Debito',
    debtAnalyzer: 'Analizzatore della Salute del Debito',
    overIndebtedness: 'Rischio di Sovraindebitamento',
    financialFreedom: 'Percorso verso la Libertà Finanziaria',
    efficiencyScore: 'Punteggio di Efficienza Finanziaria',
    optimizationFocus: 'Focus su Ottimizzazione Rigorosa',
    globalVision: 'Visione Globale degli Interessi',
    viableAlternatives: 'Alternative Viabili',
    debtFreeDate: 'Data Stimata di Libertà dal Debito',
    interestAvoided: 'Interessi Potenziali Evitati',
    totalDebtPending: 'Debito Totale Residuo',
    totalSavings: 'Risparmio Totale (Evitato)',
    timeSaved: 'Tempo Risparmiato',
    moneySaved: 'Denaro Risparmiato',
    totalAvoided: 'Totale Evitato (Interessi, IVA, Assicurazione)'
  },
  fr: {
    dashboard: 'Tableau de bord',
    loans: 'Prêts',
    budget: 'Budget',
    goals: 'Objectifs',
    assets: 'Patrimoine',
    settings: 'Paramètres',
    export: 'Exporter les données',
    import: 'Importer les données',
    summary: 'Résumé Général',
    monthlyBalance: 'Solde Mensuel',
    netWorth: 'Valeur Nette',
    goalProgress: 'Progrès des Objectifs',
    incomeVsExpenses: 'Revenus vs Dépenses',
    debtDistribution: 'Distribution de la Dette',
    newLoan: 'Nouveau Prêt',
    newGoal: 'Nouvel Objectif',
    newAsset: 'Nouvel Actif',
    language: 'Langue',
    theme: 'Thème',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    description: 'Description',
    amount: 'Montant',
    category: 'Catégorie',
    date: 'Date',
    income: 'Revenu',
    expense: 'Dépense',
    add: 'Ajouter',
    total: 'Total',
    balance: 'Solde',
    premiumPlan: 'Plan Premium',
    mortgage: 'Hypothèque',
    auto: 'Auto',
    loanName: 'Nom du Prêt',
    annualRate: 'Taux Annuel',
    years: 'Années',
    insurance: 'Assurance',
    vat: 'TVA',
    startDate: 'Date de Début',
    extraPayment: 'Paiement Supplémentaire',
    recurringExtraPayment: 'Paiement Récurrent',
    remainingMonths: 'Mois Restants',
    interest: 'Intérêt',
    principal: 'Principal',
    remainingBalance: 'Solde Restant',
    month: 'Mois',
    months: 'Mois',
    apply: 'Appliquer',
    schedule: 'Planifier',
    activeSchedules: 'Plans Actifs',
    realizedPayments: 'Paiements Réalisés',
    targetAmount: 'Montant Cible',
    currentAmount: 'Montant Actuel',
    deadline: 'Échéance',
    savings: 'Épargne',
    investment: 'Investissement',
    assetName: 'Nom de l\'Actif',
    estimatedValue: 'Valeur Estimée',
    passiveIncome: 'Revenu Passif',
    property: 'Propriété',
    other: 'Autre',
    assetsSummary: 'Résumé du Patrimoine',
    totalAssets: 'Total des Actifs',
    totalLiabilities: 'Total des Passifs',
    updateProgress: 'Mettre à jour le progrès',
    addAmount: 'Ajouter un montant',
    goalName: 'Nom de l\'objectif',
    help: 'Aide',
    helpDescription: 'Apprenez à utiliser les fonctionnalités de l\'application.',
    loansHelp: 'Gérez vos prêts et consultez leur tableau d\'amortissement.',
    budgetHelp: 'Suivez vos revenus et dépenses quotidiens.',
    goalsHelp: 'Fixez des objectifs d\'épargne et d\'investissement et suivez vos progrès.',
    assetsHelp: 'Surveillez vos propriétés et votre valeur nette.',
    settingsHelp: 'Personnalisez votre expérience et gérez les données.',
    financialTips: 'Conseils Financiers',
    getSmartAdvice: 'Obtenir des conseils intelligents',
    analyzingFinances: 'Analyse de vos finances...',
    tipsDescription: 'Recommandations personnalisées pour améliorer votre santé financière.',
    noTipsYet: 'Cliquez sur le bouton pour obtenir des conseils financiers personnalisés basés sur vos données.',
    aiAdvice: 'Conseils IA',
    totalInterestPaid: 'Intérêt Total Payé',
    totalInterestPending: 'Intérêt Total en Attente',
    finalPayoffDate: 'Date de Remboursement Final',
    projectionYears: 'Projection (Années)',
    advisorFocus: 'Focus Conseiller Financier',
    priorities: 'Priorités',
    alternatives: 'Alternatives',
    budgetAnalysis: 'Analyse du Budget',
    loanStrategies: 'Stratégies de Prêt',
    generalStrategy: 'Stratégie Générale',
    analysisType: 'Type d\'Analyse',
    potentialSavings: 'Économies Potentielles',
    qualityOfLife: 'Qualité de Vie',
    interestSavings: 'Économies d\'Intérêts',
    coveredByOthers: 'Couvert par d\'Autres',
    family: 'Famille',
    shared: 'Partagé',
    externalExpense: 'Dépense Externe (N\'affecte pas le revenu personnel)',
    totalIncome: 'Revenu Total',
    totalExpenses: 'Dépenses Totales',
    totalCoveredByOthers: 'Total Couvert par d\'Autres',
    debtTimeline: 'Chronologie de la Dette',
    debtAnalyzer: 'Analyseur de Santé de la Dette',
    overIndebtedness: 'Risque de Surendettement',
    financialFreedom: 'Chemin vers la Liberté Financière',
    efficiencyScore: 'Score d\'Efficacité Financière',
    optimizationFocus: 'Focus sur l\'Optimisation Stricte',
    globalVision: 'Vision Globale des Intérêts',
    viableAlternatives: 'Alternatives Viables',
    debtFreeDate: 'Date Estimée de Libération de la Dette',
    interestAvoided: 'Intérêts Potentiels Évités',
    totalDebtPending: 'Dette Totale Restante',
    totalSavings: 'Économies Totales (Évitées)',
    timeSaved: 'Temps Gagné',
    moneySaved: 'Argent Économisé',
    totalAvoided: 'Total Évité (Intérêts, TVA, Assurance)'
  },
  pt: {
    dashboard: 'Painel',
    loans: 'Empréstimos',
    budget: 'Orçamento',
    goals: 'Metas',
    assets: 'Patrimônio',
    settings: 'Configurações',
    export: 'Exportar Dados',
    import: 'Importar Dados',
    summary: 'Resumo Geral',
    monthlyBalance: 'Saldo Mensal',
    netWorth: 'Patrimônio Líquido',
    goalProgress: 'Progresso das Metas',
    incomeVsExpenses: 'Receitas vs Despesas',
    debtDistribution: 'Distribuição de Dívida',
    newLoan: 'Novo Empréstimo',
    newGoal: 'Nova Meta',
    newAsset: 'Novo Ativo',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    description: 'Descrição',
    amount: 'Valor',
    category: 'Categoria',
    date: 'Data',
    income: 'Receita',
    expense: 'Despesa',
    add: 'Adicionar',
    total: 'Total',
    balance: 'Saldo',
    premiumPlan: 'Plano Premium',
    mortgage: 'Hipoteca',
    auto: 'Auto',
    loanName: 'Nome do Empréstimo',
    annualRate: 'Taxa Anual',
    years: 'Anos',
    insurance: 'Seguro',
    vat: 'IVA',
    startDate: 'Data de Início',
    extraPayment: 'Pagamento Extra',
    recurringExtraPayment: 'Pagamento Extra Recorrente',
    remainingMonths: 'Meses Restantes',
    interest: 'Juros',
    principal: 'Principal',
    remainingBalance: 'Saldo Devedor',
    month: 'Mês',
    months: 'Meses',
    apply: 'Aplicar',
    schedule: 'Agendar',
    activeSchedules: 'Agendamentos Ativos',
    realizedPayments: 'Pagamentos Realizados',
    targetAmount: 'Valor Alvo',
    currentAmount: 'Valor Atual',
    deadline: 'Prazo',
    savings: 'Poupança',
    investment: 'Investimento',
    assetName: 'Nome do Ativo',
    estimatedValue: 'Valor Estimado',
    passiveIncome: 'Renda Passiva',
    property: 'Propriedade',
    other: 'Outro',
    assetsSummary: 'Resumo do Patrimônio',
    totalAssets: 'Total de Ativos',
    totalLiabilities: 'Total de Passivos',
    updateProgress: 'Atualizar Progresso',
    addAmount: 'Adicionar Valor',
    goalName: 'Nome da Meta',
    help: 'Ajuda',
    helpDescription: 'Aprenda a usar as funcionalidades do aplicativo.',
    loansHelp: 'Gerencie seus empréstimos e veja sua tabela de amortização.',
    budgetHelp: 'Acompanhe suas receitas e despesas diárias.',
    goalsHelp: 'Defina metas de poupança e investimento e acompanhe o progresso.',
    assetsHelp: 'Monitore suas propriedades e patrimônio líquido.',
    settingsHelp: 'Personalize sua experiencia e gerencie dados.',
    financialTips: 'Dicas Financeiras',
    getSmartAdvice: 'Obter Dicas Inteligentes',
    analyzingFinances: 'Analisando suas finanças...',
    tipsDescription: 'Recomendações personalizadas para melhorar sua saúde financeira.',
    noTipsYet: 'Clique no botão para obter dicas financeiras personalizadas com base em seus dados.',
    aiAdvice: 'Conselhos de IA',
    totalInterestPaid: 'Juros Totais Pagos',
    totalInterestPending: 'Juros Totais Pendentes',
    finalPayoffDate: 'Data Final de Quitação',
    projectionYears: 'Projeção (Anos)',
    advisorFocus: 'Foco do Assessor Financeiro',
    priorities: 'Prioridades',
    alternatives: 'Alternativas',
    budgetAnalysis: 'Análise de Orçamento',
    loanStrategies: 'Estratégias de Empréstimo',
    generalStrategy: 'Estrategia Geral',
    analysisType: 'Tipo de Análise',
    potentialSavings: 'Economia Potencial',
    qualityOfLife: 'Qualidade de Vida',
    interestSavings: 'Economia de Juros',
    coveredByOthers: 'Coberto por Outros',
    family: 'Família',
    shared: 'Compartilhado',
    externalExpense: 'Despesa Externa (Não afeta renda pessoal)',
    totalIncome: 'Renda Total',
    totalExpenses: 'Despesas Totais',
    totalCoveredByOthers: 'Total Coberto por Outros',
    debtTimeline: 'Linha do Tempo da Dívida',
    debtAnalyzer: 'Analisador de Saúde da Dívida',
    overIndebtedness: 'Risco de Sobre-endividamento',
    financialFreedom: 'Caminho para a Liberdade Financeira',
    efficiencyScore: 'Pontuação de Eficiência Financiera',
    optimizationFocus: 'Foco em Otimização Estrita',
    globalVision: 'Visão Global de Juros',
    viableAlternatives: 'Alternativas Viáveis',
    debtFreeDate: 'Data Estimada de Liberdade de Dívida',
    interestAvoided: 'Juros Potenciais Evitados',
    totalDebtPending: 'Dívida Total Pendente',
    totalSavings: 'Economia Total (Evitada)',
    timeSaved: 'Tempo Economizado',
    moneySaved: 'Dinheiro Economizado',
    totalAvoided: 'Total Evitado (Juros, IVA, Seguros)'
  },
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('finpro_lang') as Language) || 'es';
  });
  const [theme, setTheme] = useState<Theme>(() => {
    return (localStorage.getItem('finpro_theme') as Theme) || 'light';
  });

  useEffect(() => {
    localStorage.setItem('finpro_lang', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('finpro_theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <SettingsContext.Provider value={{ language, theme, setLanguage, setTheme, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
}
